###Obtener todas las películas
GET http://localhost:1234/movies


###Encontrar una pelicula por id
GET http://localhost:1234/movies/1467F5A2-01D9-4872-87A9-A553F0EE1ACB
###Encontrar pelicula por género
GET http://localhost:1234/movies?genre=09iji123123

###Eliminar una pelicula por id
DELETE http://localhost:1234/movies/7FD57B69-4B37-4E18-A899-165AE6186052

###Crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "Spiderman far from",
    "year": 2019,
    "director": "Rusos Brothers",
    "duration": 132,
    "poster": "https://cdn.marvel.com/content/1x/spider-manfarfromhome_lob_crd_04_0.jpg",
    "genre": ["Action", "Drama"]
}

###Actualizar una pelicula
PATCH http://localhost:1234/movies/1467F5A2-01D9-4872-87A9-A553F0EE1ACB
Content-Type:  application/json

{
    "title": "Iron man",
    "year": 2009,
    "director": "Rusos Brothers",
    "duration": 142,
    "poster": "https://es.web.img3.acsta.net/c_300_300/img/30/23/30232de235a8bca8533f5ddb06fef0dd.jpg"
}